project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - text: "Proposal"
      href: "pages/proposal.html"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

